pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
       stage('sonarcloud analysis'){
            steps{
                withSonarQubeEnv('sonarQube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rivelino86_Geo-app1'
              }
            }    
          }
        stage("maven"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
              sh 'curl -uadmin:AP9zz3w2porBznMWtvBy9Pw9eM4 -T <PATH_TO_FILE> \
              target/bio*.jar \
              "http://ec2-52-86-176-43.compute-1.amazonaws.com:8081/artifactory/Geolocation/geo/bio_${BUILD_ID}.jar"'
        }
        }
        stage("docker login"){
          steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin 655040006853.dkr.ecr.us-east-1.amazonaws.com'
          }
        }
      }
    }