pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
       stage('sonarcloud analysis'){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rivelino86_Geo-app1'
            }
          }
        stage("maven"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
       
        }
      }
    }